### PR TITLE
Adding doubloons to the token list

### PR DESCRIPTION
**Pull request by dutchiekiwi**
Doubloons are the in game currency for the damedpiratessociety (DPS) on the moonriver blockchain

### CODE REVIEW

**Comment by carrion9** [comment]
Add token's info in the community.tokenlist.json file instead of solarbeam.tokenlist.json

**Comment by carrion9** [comment]
Please add token's info in the community.tokenlist.json file instead of solarbeam.tokenlist.json

**Comment by dutchiekiwi** [comment]
Sorry about that, i have removed from the incorrect tokenlist and put the token info in the community list.

**Comment by carrion9** [comment]
No worries, can you also change the name to DPSDoubloon and symbol to DOUBLOON, as it is in your token's contract deployment, in order to avoid conflicts?

**Comment by carrion9** [comment]
Also, change doubloons.PNG filename to logo.png

**Comment by dutchiekiwi** [comment]
I have implemented the changes, hopefully this time i have got it all correct. Thanks :)

**Comment by carrion9** [comment]
Merged! cheers :)

**Pull request merged**
